# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib

from show import chart

matplotlib.use("Qt5Agg")  # 声明使用QT5

matplotlib.rcParams['font.sans-serif'] = ['SimHei']  # 设置字体为SimHei显示中文
matplotlib.rcParams['font.size'] = 14  # 设置字体大小
matplotlib.rcParams['axes.unicode_minus'] = False  # 设置正常显示字符，使用rc配置文件来自定义


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        MainWindow.setStyleSheet("border-image: url(:/images/images/00004.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, -10, 270, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image: url();\n"
                                 "color: rgb(255, 255, 0)")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 80, 240, 731))
        self.widget.setStyleSheet("border-image: url();\n"
                                  "background-color: rgb(61, 113, 255);")
        self.widget.setObjectName("widget")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(0, 130, 311, 16))
        self.line_2.setStyleSheet("border-image: url();\n"
                                  "background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(0, 280, 311, 16))
        self.line_3.setStyleSheet("border-image: url();\n"
                                  "background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(0, 430, 311, 16))
        self.line_4.setStyleSheet("border-image: url();\n"
                                  "background-color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(0, 580, 311, 16))
        self.line_5.setStyleSheet("border-image: url();\n"
                                  "background-color: rgb(255, 255, 255);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 220, 110))
        self.pushButton.setStyleSheet("#pushButton{\n"
                                      "color:rgb(186,186,186);\n"
                                      "font:25pt \"黑体\";\n"
                                      "border:none;\n"
                                      "}\n"
                                      "#pushButton:focus{\n"
                                      "background-color:rgba(255,255,255,0);\n"
                                      "color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 160, 220, 110))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"黑体\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_2:focus{\n"
                                        "background-color:rgba(255,255,255,0);\n"
                                        "color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 310, 220, 110))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"黑体\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_3:focus{\n"
                                        "background-color:rgba(255,255,255,0);\n"
                                        "color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 460, 220, 110))
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"黑体\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_4:focus{\n"
                                        "background-color:rgba(255,255,255,0);\n"
                                        "color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 600, 220, 110))
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"黑体\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_5:focus{\n"
                                        "background-color:rgba(255,255,255,0);\n"
                                        "color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 80, 16, 721))
        self.line.setStyleSheet("border-image: url(rgb(255, 255, 127));\n"
                                "background-color: rgb(255, 255, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(270, 80, 920, 710))
        self.groupBox.setStyleSheet("border-image: url();\n"
                                    "border:none;")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 80, 920, 710))
        self.groupBox_2.setStyleSheet("border-image: url();\n"
                                      "background-color:rgba(0,0,0,0);\n"
                                      "border:none;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 80, 920, 710))
        self.groupBox_3.setStyleSheet("border-image: url();\n"
                                      "border:none;")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(270, 80, 920, 710))
        self.groupBox_4.setStyleSheet("border-image: url();\n"
                                      "border:none;")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(270, 80, 920, 710))
        self.groupBox_5.setStyleSheet("border-image: url();\n"
                                      "border:none;")
        self.groupBox_5.setObjectName("groupBox_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # 显示图像
        self.price_plots2()
        self.pushButton.clicked.connect(self.charge_1)
        self.pushButton_2.clicked.connect(self.charge_2)
        self.pushButton_3.clicked.connect(self.charge_3)
        self.pushButton_4.clicked.connect(self.charge_4)
        self.pushButton_5.clicked.connect(self.charge_5)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 默认显示第一个
        self.groupBox.show()
        self.groupBox_2.hide()
        self.groupBox_3.hide()
        self.groupBox_4.hide()
        self.groupBox_5.hide()

    def charge_1(self):
        self.groupBox.show()
        self.groupBox_2.hide()
        self.groupBox_3.hide()
        self.groupBox_4.hide()
        self.groupBox_5.hide()
        self.price_plots2()

    def charge_2(self):
        self.groupBox.hide()
        self.groupBox_2.show()
        self.groupBox_3.hide()
        self.groupBox_4.hide()
        self.groupBox_5.hide()
        self.price_chart()

    def charge_3(self):
        self.groupBox.hide()
        self.groupBox_2.hide()
        self.groupBox_3.show()
        self.groupBox_4.hide()
        self.groupBox_5.hide()
        self.price_plots()

    def charge_4(self):
        self.groupBox.hide()
        self.groupBox_2.hide()
        self.groupBox_3.hide()
        self.groupBox_4.show()
        self.groupBox_5.hide()
        self.price_bar()

    def charge_5(self):
        self.groupBox.hide()
        self.groupBox_2.hide()
        self.groupBox_3.hide()
        self.groupBox_4.hide()
        self.groupBox_5.show()
        self.forecast_plots()

    def price_bar(self):
        QtWidgets.QGridLayout(self.groupBox_4).addWidget(chart.hot_portal_barh())

    def price_chart(self):
        QtWidgets.QGridLayout(self.groupBox_2).addWidget(chart.proportional_quantity_pie())

    def price_plots(self):
        QtWidgets.QGridLayout(self.groupBox_3).addWidget(chart.buildyears_averagePractice_plots())

    def price_plots2(self):
        QtWidgets.QGridLayout(self.groupBox).addWidget(chart.district_averagePractice_plots())

    def forecast_plots(self):
        QtWidgets.QGridLayout(self.groupBox_5).addWidget(chart.forecast_plots())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "二手房软件"))
        self.pushButton.setText(_translate("MainWindow", "均价分析"))
        self.pushButton_2.setText(_translate("MainWindow", "数量比例"))
        self.pushButton_3.setText(_translate("MainWindow", "装修程度"))
        self.pushButton_4.setText(_translate("MainWindow", "热门户型"))
        self.pushButton_5.setText(_translate("MainWindow", "预测分析"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))


import resources.secondHandHouse_rc
